/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import { GlobalComponents } from 'vue'

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Backtop: typeof import('./../components/Backtop/src/Backtop.vue')['default']
    ConfigGlobal: typeof import('./../components/ConfigGlobal/src/ConfigGlobal.vue')['default']
    ContentWrap: typeof import('./../components/ContentWrap/src/ContentWrap.vue')['default']
    CopperModal: typeof import('./../components/Cropper/src/CopperModal.vue')['default']
    Cropper: typeof import('./../components/Cropper/src/Cropper.vue')['default']
    CropperAvatar: typeof import('./../components/Cropper/src/CropperAvatar.vue')['default']
    Dialog: typeof import('./../components/Dialog/src/Dialog.vue')['default']
    DictTag: typeof import('./../components/DictTag/src/DictTag.vue')['default']
    DocAlert: typeof import('./../components/DocAlert/index.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    Error: typeof import('./../components/Error/src/Error.vue')['default']
    Form: typeof import('./../components/Form/src/Form.vue')['default']
    Icon: typeof import('./../components/Icon/src/Icon.vue')['default']
    InputPassword: typeof import('./../components/InputPassword/src/InputPassword.vue')['default']
    Pagination: typeof import('./../components/Pagination/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterSearch: typeof import('./../components/RouterSearch/index.vue')['default']
    RouterView: typeof import('vue-router')['RouterView']
    Verify: typeof import('./../components/Verifition/src/Verify.vue')['default']
    VerifyPictureWord: typeof import('./../components/Verifition/src/Verify/VerifyPictureWord.vue')['default']
    VerifyPoints: typeof import('./../components/Verifition/src/Verify/VerifyPoints.vue')['default']
    VerifySlide: typeof import('./../components/Verifition/src/Verify/VerifySlide.vue')['default']
  }
}

// For TSX support
declare global {
  const Backtop: typeof import('./../components/Backtop/src/Backtop.vue')['default']
  const ConfigGlobal: typeof import('./../components/ConfigGlobal/src/ConfigGlobal.vue')['default']
  const ContentWrap: typeof import('./../components/ContentWrap/src/ContentWrap.vue')['default']
  const CopperModal: typeof import('./../components/Cropper/src/CopperModal.vue')['default']
  const Cropper: typeof import('./../components/Cropper/src/Cropper.vue')['default']
  const CropperAvatar: typeof import('./../components/Cropper/src/CropperAvatar.vue')['default']
  const Dialog: typeof import('./../components/Dialog/src/Dialog.vue')['default']
  const DictTag: typeof import('./../components/DictTag/src/DictTag.vue')['default']
  const DocAlert: typeof import('./../components/DocAlert/index.vue')['default']
  const ElButton: typeof import('element-plus/es')['ElButton']
  const ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
  const ElCol: typeof import('element-plus/es')['ElCol']
  const ElDialog: typeof import('element-plus/es')['ElDialog']
  const ElDropdown: typeof import('element-plus/es')['ElDropdown']
  const ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
  const ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
  const ElForm: typeof import('element-plus/es')['ElForm']
  const ElFormItem: typeof import('element-plus/es')['ElFormItem']
  const ElIcon: typeof import('element-plus/es')['ElIcon']
  const ElInput: typeof import('element-plus/es')['ElInput']
  const ElOption: typeof import('element-plus/es')['ElOption']
  const ElRow: typeof import('element-plus/es')['ElRow']
  const ElSelect: typeof import('element-plus/es')['ElSelect']
  const Error: typeof import('./../components/Error/src/Error.vue')['default']
  const Form: typeof import('./../components/Form/src/Form.vue')['default']
  const Icon: typeof import('./../components/Icon/src/Icon.vue')['default']
  const InputPassword: typeof import('./../components/InputPassword/src/InputPassword.vue')['default']
  const Pagination: typeof import('./../components/Pagination/index.vue')['default']
  const RouterLink: typeof import('vue-router')['RouterLink']
  const RouterSearch: typeof import('./../components/RouterSearch/index.vue')['default']
  const RouterView: typeof import('vue-router')['RouterView']
  const Verify: typeof import('./../components/Verifition/src/Verify.vue')['default']
  const VerifyPictureWord: typeof import('./../components/Verifition/src/Verify/VerifyPictureWord.vue')['default']
  const VerifyPoints: typeof import('./../components/Verifition/src/Verify/VerifyPoints.vue')['default']
  const VerifySlide: typeof import('./../components/Verifition/src/Verify/VerifySlide.vue')['default']
}
