/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import { GlobalComponents } from 'vue'

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Backtop: typeof import('./../components/Backtop/src/Backtop.vue')['default']
    ConfigGlobal: typeof import('./../components/ConfigGlobal/src/ConfigGlobal.vue')['default']
    ContentDetailWrap: typeof import('./../components/ContentDetailWrap/src/ContentDetailWrap.vue')['default']
    ContentWrap: typeof import('./../components/ContentWrap/src/ContentWrap.vue')['default']
    CopperModal: typeof import('./../components/Cropper/src/CopperModal.vue')['default']
    Crontab: typeof import('./../components/Crontab/src/Crontab.vue')['default']
    Cropper: typeof import('./../components/Cropper/src/Cropper.vue')['default']
    CropperAvatar: typeof import('./../components/Cropper/src/CropperAvatar.vue')['default']
    Dialog: typeof import('./../components/Dialog/src/Dialog.vue')['default']
    DictTag: typeof import('./../components/DictTag/src/DictTag.vue')['default']
    DocAlert: typeof import('./../components/DocAlert/index.vue')['default']
    Error: typeof import('./../components/Error/src/Error.vue')['default']
    Form: typeof import('./../components/Form/src/Form.vue')['default']
    Highlight: typeof import('./../components/Highlight/src/Highlight.vue')['default']
    Icon: typeof import('./../components/Icon/src/Icon.vue')['default']
    IconSelect: typeof import('./../components/Icon/src/IconSelect.vue')['default']
    IFrame: typeof import('./../components/IFrame/src/IFrame.vue')['default']
    ImageViewer: typeof import('./../components/ImageViewer/src/ImageViewer.vue')['default']
    Infotip: typeof import('./../components/Infotip/src/Infotip.vue')['default']
    InputPassword: typeof import('./../components/InputPassword/src/InputPassword.vue')['default']
    Pagination: typeof import('./../components/Pagination/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterSearch: typeof import('./../components/RouterSearch/index.vue')['default']
    RouterView: typeof import('vue-router')['RouterView']
    Search: typeof import('./../components/Search/src/Search.vue')['default']
    Sticky: typeof import('./../components/Sticky/src/Sticky.vue')['default']
    Table: typeof import('./../components/Table/src/Table.vue')['default']
    TableSelectForm: typeof import('./../components/Table/src/TableSelectForm.vue')['default']
    Tooltip: typeof import('./../components/Tooltip/src/Tooltip.vue')['default']
    UploadFile: typeof import('./../components/UploadFile/src/UploadFile.vue')['default']
    UploadImg: typeof import('./../components/UploadFile/src/UploadImg.vue')['default']
    UploadImgs: typeof import('./../components/UploadFile/src/UploadImgs.vue')['default']
    Verify: typeof import('./../components/Verifition/src/Verify.vue')['default']
    VerifyPictureWord: typeof import('./../components/Verifition/src/Verify/VerifyPictureWord.vue')['default']
    VerifyPoints: typeof import('./../components/Verifition/src/Verify/VerifyPoints.vue')['default']
    VerifySlide: typeof import('./../components/Verifition/src/Verify/VerifySlide.vue')['default']
  }
}

// For TSX support
declare global {
  const Backtop: typeof import('./../components/Backtop/src/Backtop.vue')['default']
  const ConfigGlobal: typeof import('./../components/ConfigGlobal/src/ConfigGlobal.vue')['default']
  const ContentDetailWrap: typeof import('./../components/ContentDetailWrap/src/ContentDetailWrap.vue')['default']
  const ContentWrap: typeof import('./../components/ContentWrap/src/ContentWrap.vue')['default']
  const CopperModal: typeof import('./../components/Cropper/src/CopperModal.vue')['default']
  const Crontab: typeof import('./../components/Crontab/src/Crontab.vue')['default']
  const Cropper: typeof import('./../components/Cropper/src/Cropper.vue')['default']
  const CropperAvatar: typeof import('./../components/Cropper/src/CropperAvatar.vue')['default']
  const Dialog: typeof import('./../components/Dialog/src/Dialog.vue')['default']
  const DictTag: typeof import('./../components/DictTag/src/DictTag.vue')['default']
  const DocAlert: typeof import('./../components/DocAlert/index.vue')['default']
  const Error: typeof import('./../components/Error/src/Error.vue')['default']
  const Form: typeof import('./../components/Form/src/Form.vue')['default']
  const Highlight: typeof import('./../components/Highlight/src/Highlight.vue')['default']
  const Icon: typeof import('./../components/Icon/src/Icon.vue')['default']
  const IconSelect: typeof import('./../components/Icon/src/IconSelect.vue')['default']
  const IFrame: typeof import('./../components/IFrame/src/IFrame.vue')['default']
  const ImageViewer: typeof import('./../components/ImageViewer/src/ImageViewer.vue')['default']
  const Infotip: typeof import('./../components/Infotip/src/Infotip.vue')['default']
  const InputPassword: typeof import('./../components/InputPassword/src/InputPassword.vue')['default']
  const Pagination: typeof import('./../components/Pagination/index.vue')['default']
  const RouterLink: typeof import('vue-router')['RouterLink']
  const RouterSearch: typeof import('./../components/RouterSearch/index.vue')['default']
  const RouterView: typeof import('vue-router')['RouterView']
  const Search: typeof import('./../components/Search/src/Search.vue')['default']
  const Sticky: typeof import('./../components/Sticky/src/Sticky.vue')['default']
  const Table: typeof import('./../components/Table/src/Table.vue')['default']
  const TableSelectForm: typeof import('./../components/Table/src/TableSelectForm.vue')['default']
  const Tooltip: typeof import('./../components/Tooltip/src/Tooltip.vue')['default']
  const UploadFile: typeof import('./../components/UploadFile/src/UploadFile.vue')['default']
  const UploadImg: typeof import('./../components/UploadFile/src/UploadImg.vue')['default']
  const UploadImgs: typeof import('./../components/UploadFile/src/UploadImgs.vue')['default']
  const Verify: typeof import('./../components/Verifition/src/Verify.vue')['default']
  const VerifyPictureWord: typeof import('./../components/Verifition/src/Verify/VerifyPictureWord.vue')['default']
  const VerifyPoints: typeof import('./../components/Verifition/src/Verify/VerifyPoints.vue')['default']
  const VerifySlide: typeof import('./../components/Verifition/src/Verify/VerifySlide.vue')['default']
}
